### Buổi 3: Phân tích dữ liệu

In [ ]:
!rm -r pydata-book
!git clone https://github.com/wesm/pydata-book.git
!ls pydata-book/
!sudo rm -r pydata-book/.git

In [ ]:
!git status
!git add . -n
!git add .
!git commit -m "buoi03"
!git push
!git status
!git push --force # ép phải commit (nếu xảy ra xung đột)
!git reset HEAD~  # phục hồi lại trạng thái commit gần nhất

!git add .
!git commit -m "buoi03"
!git push

In [ ]:
!ls
!mv pydata-book/ ../
!git add . -n
!git add .
!git commit -m "buoi03"
!git push

In [3]:
v = list(range(1, 6))
v
2 * v
import numpy as np
v = np.arange(1, 6)
v
2 * v

array([ 2,  4,  6,  8, 10])

In [4]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [5]:
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90


In [6]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
c

array([ 4, 10, 18])

In [7]:
import numpy as np
a = np.arange(15).reshape(3, 5)

In [8]:
a.shape

(3, 5)

In [9]:
a.ndim

2

In [10]:
a.dtype.name

'int64'

In [11]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [12]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
import numpy as np
a = np.array([[0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [14]:
a = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])