### Buổi 3: Phân tích dữ liệu

In [ ]:
!rm -r pydata-book
!git clone https://github.com/wesm/pydata-book.git
!ls pydata-book/
!sudo rm -r pydata-book/.git

In [ ]:
!git status
!git add . -n
!git add .
!git commit -m "buoi03"
!git push
!git status
!git push --force # ép phải commit (nếu xảy ra xung đột)
!git reset HEAD~  # phục hồi lại trạng thái commit gần nhất

!git add .
!git commit -m "buoi03"
!git push

In [ ]:
!ls
!mv pydata-book/ ../
!git add . -n
!git add .
!git commit -m "buoi03"
!git push

In [3]:
v = list(range(1, 6))
v
2 * v
import numpy as np
v = np.arange(1, 6)
v
2 * v

array([ 2,  4,  6,  8, 10])

In [4]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [5]:
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90


In [6]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
c

array([ 4, 10, 18])

In [7]:
import numpy as np
a = np.arange(15).reshape(3, 5)

In [8]:
a.shape

(3, 5)

In [9]:
a.ndim

2

In [10]:
a.dtype.name

'int64'

In [11]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [12]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
import numpy as np
a = np.array([[0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [14]:
a = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

### Pandas

In [16]:
import pandas as pd
df = pd.DataFrame({"a": [4, 5, 6],
"b": [7, 8, 9],
"c": [10, 11, 12]},
index = [1, 2, 3])

In [17]:
type(df)

pandas.core.frame.DataFrame

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('pandas imported')

pandas imported


In [19]:
s = pd.Series([1,3,5,np.nan,6,8])
s


0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [20]:
dates = pd.date_range('20181001',
periods=6)
dates

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [21]:
df = pd.DataFrame(np.random.randn(6,4),
index=dates, columns=list('ABCD'))
df

A         B         C         D
2018-10-01 -0.462651  0.684765 -1.871037 -1.121476
2018-10-02  1.262310 -0.168490 -1.092110 -0.778098
2018-10-03  0.862566  0.468653 -0.187759 -0.990531
2018-10-04 -0.470186  0.631139 -0.635154  0.714754
2018-10-05 -0.640770  0.263108  0.067927  0.273172
2018-10-06 -1.028079  1.511333 -0.108084 -1.839771

In [22]:
df = pd.DataFrame(np.random.randn(3,5),
index=['student1','student2','student3']
, columns=list('ABCDE'))
df

A         B         C         D         E
student1 -0.682808  1.516052  0.626260 -0.518195  0.033618
student2  0.510005  0.708468  0.920546 -1.350245 -0.289005
student3 -0.210222 -0.545220  0.909526  1.254991  0.613242

In [23]:
df2 = pd.DataFrame({ 'A' : 1.,
'B' : pd.Timestamp('20181001'),
'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
'D' : np.array([3] * 4,dtype='int32'),
'E' : pd.Categorical(["test","train","test","train"]),
'F' : 'foo' })
df2

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [24]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object